#!/usr/bin/env bash
# Regenerate the pinned requirement files from pdm.lock, the same way every
# time. Run from the repo root after editing pyproject.toml.
#
#   requirements.txt          the base install (default group). No PDF, no torch.
#   requirements-pdf-gpu.txt  the `pdf` extra as locked: PyPI's PyTorch, which
#                             on Linux is the CUDA build (821 MB plus ~2.16 GB
#                             of nvidia/triton wheels, at torch 2.7.1)
#   requirements-pdf-cpu.txt  the same requirements, fetched from PyTorch's CPU
#                             index instead (176 MB, no nvidia wheels)
#
# The extra is exported without the default group so it is installed after
# requirements.txt, each file self-contained for pip's hash-checking mode.
# `--update-reuse` keeps every pin the lock already has, so a change to one
# group does not move the others.
#
# Why the CPU file is different in kind, and carries no hashes
# -----------------------------------------------------------
# Which PyTorch build you get is an INDEX choice, not a version one, and a
# lock file cannot express it: `torch==2.14.0` and `torch==2.14.0+cpu` are
# the same release built twice and published to two indexes, with different
# wheels and therefore different hashes. A hash-pinned file can name only
# one of them. So the CPU file names the index in the file itself -- pip
# reads `--extra-index-url` from a requirements file -- and drops the hashes
# it could not satisfy. The operator has no flag to remember; the cost is
# that this one file is not hash-checked.
#
# `==2.7.1` matches `2.7.1+cpu` under PEP 440 (a specifier without a local
# version matches one with it), and pip prefers the local version as the
# higher candidate, so the CPU index wins for torch while everything else
# still comes from PyPI.
#
# The nvidia-*/triton pins are stripped from the CPU file as well. They are
# in the lock because PyPI's torch REQUIRES them; the +cpu build requires
# none of them (verified: zero nvidia entries in its metadata). Leaving the
# lines in would install ~1.6 GB of CUDA beside a CPU torch that never
# touches it -- the exact thing this file exists to avoid.
#
# The split is real on Linux only. On macOS and Windows the PyPI wheel is
# already CPU-only, so both files install the same thing there. See
# docs/installation-pdf.md.
set -euo pipefail
cd "$(dirname "$0")/.."
pdm lock --update-reuse -G :all
pdm export --prod -o requirements.txt
pdm export --prod --no-default -G pdf -o requirements-pdf-gpu.txt
{
  echo "# The PDF extra, from PyTorch's CPU index: no CUDA wheels."
  echo "# Generated by tools/export_requirements.sh -- do not edit manually."
  echo "# Unhashed by necessity; see that script for why."
  echo "--extra-index-url https://download.pytorch.org/whl/cpu"
  echo
  pdm export --prod --no-default -G pdf --no-hashes \
    | grep -v '^#' \
    | grep -vE '^(nvidia-[a-z0-9-]+|triton|pytorch-triton)=='
} > requirements-pdf-cpu.txt
